import 'package:flutter/material.dart';
import '../admin_api_client.dart';
import '../admin_models.dart';
import '../admin_theme.dart';
import '../admin_widgets.dart';

class AdminCmsScreen extends StatefulWidget { final AdminApiClient? api; final bool dark; const AdminCmsScreen({super.key,this.api,required this.dark}); @override State<AdminCmsScreen> createState()=>_AdminCmsScreenState(); }
class _AdminCmsScreenState extends State<AdminCmsScreen>{
  bool get dark => widget.dark;
  bool coding=true; String difficulty='Medium'; final title=TextEditingController(),topic=TextEditingController(),details=TextEditingController(),boilerplate=TextEditingController();
  final List<AdminQuestion> questions=[
    const AdminQuestion(id:'1',type:'coding',title:'Distributed Memory Token Ring',difficulty:'Hard',topic:'Systems & Concurrency',details:'Simulate a dynamic thread-safe Token Ring passing memory references across N virtual channels without lock overlaps.',boilerplate:'class TokenRing {\n  public void passToken(int nodeId, Object memoryBuffer) {\n    // Implement lock-free concurrent passage\n  }\n}',published:true),
    const AdminQuestion(id:'2',type:'reasoning',title:'Binary Tree Network Throughput',difficulty:'Medium',topic:'Network Topology Logic',details:'Determine the maximum path bottleneck rate of a binary decision network when three alternate pipelines run concurrently.',boilerplate:'',published:true),
    const AdminQuestion(id:'3',type:'coding',title:'Two-Pointer Sliding Window Optimizations',difficulty:'Medium',topic:'Core Algorithms',details:'Scan a sequence of continuous logs and identify the longest interval where CPU load remains strictly below 90%.',boilerplate:'def solution_name(arg):\n    # Write logic...',published:false),
  ];
  @override void dispose(){for(final c in [title,topic,details,boilerplate])c.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>SingleChildScrollView(padding:const EdgeInsets.fromLTRB(44,38,44,60),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:1420),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    AdminPageHeader(dark:dark,badge:'SUPER ADMIN CONTROL NODE',title:'SaaS Global Mainframe Management',subtitle:'Configure multi-tenant limits, allocate compiler limits, input API keys, and publish master curriculum libraries.'),
    const SizedBox(height:28),_roadmaps(),const SizedBox(height:24),
    LayoutBuilder(builder:(_,c)=>c.maxWidth<980?Column(children:[_composer(),const SizedBox(height:20),_bank()]):Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:5,child:_composer()),const SizedBox(width:24),Expanded(flex:8,child:_bank())])),
  ]))));
  Widget _roadmaps()=>Container(padding:const EdgeInsets.fromLTRB(28,25,28,27),decoration:AdminTheme.cardDecoration(dark,radius:24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Master Curriculum Roadmaps Templates',style:AdminText.section(dark)),const SizedBox(height:5),Text('Universal course timelines available to push to college tenants instantly.',style:TextStyle(color:AdminTheme.secondary(dark),fontSize:11))])),AdminActionButton(label:'Broadcast CMS Templates to All Tenants',icon:Icons.wifi_tethering_rounded,color:AdminTheme.purple,onPressed:(){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('CMS templates broadcast to all tenants.')));})]),const SizedBox(height:22),Row(children:[Expanded(child:_template('Syllabus template: Full-Stack Web Dev (React & TS)','5 Core Levels • 15 Lessons • 12 Embedded Quizzes')),const SizedBox(width:18),Expanded(child:_template('Syllabus template: Python & Artificial Intelligence','5 Core Levels • 18 Lessons • 14 Integrated Compiler Tests'))])]));
  Widget _template(String a,String b)=>Container(height:74,padding:const EdgeInsets.symmetric(horizontal:18),alignment:Alignment.centerLeft,decoration:BoxDecoration(color:dark ? const Color(0xFF171E2D) : const Color(0xFFFAFBFC),borderRadius:BorderRadius.circular(16),border:Border.all(color:AdminTheme.outline(dark))),child:Row(children:[Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:TextStyle(color:AdminTheme.foreground(dark),fontSize:11.5,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text(b,style:TextStyle(color:AdminTheme.secondary(dark),fontSize:9.5))])),AdminBadge(text:'STANDARD',color:AdminTheme.green)]));
  Widget _composer()=>Container(padding:const EdgeInsets.fromLTRB(28,26,28,27),decoration:AdminTheme.cardDecoration(dark,radius:24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.add_circle_outline,color:AdminTheme.primary),const SizedBox(width:10),Text('Queue Question Template',style:AdminText.section(dark))]),const SizedBox(height:5),Text('Insert universal coding compiler or logical aptitude challenges to push downstream.',style:TextStyle(color:AdminTheme.secondary(dark),fontSize:11)),const SizedBox(height:23),Text('Question Format',style:AdminText.label(dark)),const SizedBox(height:7),Row(children:[Expanded(child:_formatButton('💻 Coding Challenge',coding,()=>setState(()=>coding=true))),const SizedBox(width:9),Expanded(child:_formatButton('🧩 Logical Aptitude',!coding,()=>setState(()=>coding=false)))]),const SizedBox(height:17),AdminInput(label:'Challenge Title',hint:'e.g. Reverse Linked List Elements',controller:title,dark:dark),const SizedBox(height:16),Row(children:[Expanded(child:AdminInput(label:'Topic Area',hint:'e.g. Data Structures',controller:topic,dark:dark)),const SizedBox(width:12),Expanded(child:_difficulty())]),const SizedBox(height:16),AdminInput(label:'Description & Rules',hint:'Describe problem statement and logic constraints...',controller:details,dark:dark,maxLines:4),const SizedBox(height:16),AdminInput(label:'Code Boilerplate',hint:'def solution_name(arg):\n  # Write logic...',controller:boilerplate,dark:dark,maxLines:4),const SizedBox(height:18),AdminActionButton(label:'Add to Global Master Repository',icon:Icons.add_rounded,color:AdminTheme.purple,onPressed:_add)]));
  Widget _formatButton(String label,bool active,VoidCallback tap)=>SizedBox(height:44,child:OutlinedButton(onPressed:tap,style:OutlinedButton.styleFrom(foregroundColor:active?AdminTheme.purple:AdminTheme.secondary(dark),side:BorderSide(color:active?AdminTheme.purple:AdminTheme.outline(dark)),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12))),child:Text(label,style:const TextStyle(fontSize:10.5,fontWeight:FontWeight.w900))));
  Widget _difficulty() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Complexity', style: AdminText.label(dark)),
        const SizedBox(height: 7),
        DropdownButtonFormField<String>(
          value: difficulty,
          items: ['Easy', 'Medium', 'Hard'].map((v) => DropdownMenuItem<String>(value: v, child: Text(v, style: TextStyle(color: AdminTheme.foreground(dark), fontSize: 11.5, fontWeight: FontWeight.w700)))).toList(),
          onChanged: (v) { if (v != null) setState(() => difficulty = v); },
          decoration: InputDecoration(
            filled: true,
            fillColor: dark ? const Color(0xFF0F1522) : const Color(0xFFF8F9FB),
            contentPadding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: AdminTheme.outline(dark))),
            enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: AdminTheme.outline(dark))),
          ),
        ),
      ],
    );
  }

  Widget _bank()=>Container(padding:const EdgeInsets.fromLTRB(28,26,28,24),decoration:AdminTheme.cardDecoration(dark,radius:24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Master Bank Database Registry',style:AdminText.section(dark)),const SizedBox(height:5),Text('Live catalog of universal code and reasoning test vectors.',style:TextStyle(color:AdminTheme.secondary(dark),fontSize:11)),const SizedBox(height:20),ConstrainedBox(constraints:const BoxConstraints(maxHeight:560),child:ListView.separated(shrinkWrap:true,itemCount:questions.length,separatorBuilder:(_,__)=>const SizedBox(height:12),itemBuilder:(_,i)=>_question(questions[i])))]));
  Widget _question(AdminQuestion q)=>Container(padding:const EdgeInsets.fromLTRB(18,17,18,18),decoration:BoxDecoration(color:AdminTheme.card(dark),borderRadius:BorderRadius.circular(17),border:Border.all(color:AdminTheme.foreground(dark),width:.9)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[AdminBadge(text:q.type=='coding'?'💻 CODE CHALLENGE':'🧩 REASONING QUIZ',color:q.type=='coding'?AdminTheme.blue:AdminTheme.green),const SizedBox(width:8),AdminBadge(text:q.difficulty.toUpperCase(),color:q.difficulty=='Hard'?AdminTheme.red:AdminTheme.yellow),const SizedBox(width:9),Expanded(child:Text(q.topic,style:TextStyle(color:AdminTheme.secondary(dark),fontSize:9.5))) ,IconButton(onPressed:(){setState(()=>questions.remove(q));},icon:const Icon(Icons.delete_outline,color:AdminTheme.red,size:19))]),const SizedBox(height:8),Text(q.title,style:TextStyle(color:AdminTheme.foreground(dark),fontSize:12.5,fontWeight:FontWeight.w900)),const SizedBox(height:7),Text(q.details,style:TextStyle(color:AdminTheme.secondary(dark),fontSize:10.5,height:1.45)),if(q.boilerplate.isNotEmpty)...[const SizedBox(height:10),Container(width:double.infinity,padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:dark ? const Color(0xFF1A2230) : const Color(0xFFF3F4F6),borderRadius:BorderRadius.circular(9)),child:Text(q.boilerplate,style:TextStyle(color:AdminTheme.secondary(dark),fontSize:8.5,fontFamily:'monospace')))],const SizedBox(height:8),Row(children:[const Spacer(),Switch(value:q.published,onChanged:(v){final i=questions.indexOf(q);if(i>=0)setState(()=>questions[i]=AdminQuestion(id:q.id,type:q.type,title:q.title,difficulty:q.difficulty,topic:q.topic,details:q.details,boilerplate:q.boilerplate,published:v));},activeThumbColor:AdminTheme.green)])]));
  void _add(){if(title.text.trim().isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Challenge title is required.')));return;}setState(()=>questions.insert(0,AdminQuestion(id:DateTime.now().microsecondsSinceEpoch.toString(),type:coding?'coding':'reasoning',title:title.text.trim(),difficulty:difficulty,topic:topic.text.trim().isEmpty?'General':topic.text.trim(),details:details.text.trim(),boilerplate:boilerplate.text.trim(),published:false)));for(final c in [title,topic,details,boilerplate])c.clear();}
}
